### ISSUE TITLE
Failure to Upgrade.

### ISSUE THREAD

**Issue by brimwats1** [YunoHost-Apps/languagetool_ynh#12]
here are the two logs

https://paste.yunohost.org/raw/ufenapojik

https://paste.yunohost.org/raw/cusinexiti

**Comment by yalh76** [comment]
Can you try with last version

**Comment by brimwats** [comment]
I am not yet seeing a new version, is it just on a different branch?

**Comment by yalh76** [comment]
nope, there is at least version 5.8~ynh1, since @brimwats1 opened this issue
