### ISSUE TITLE
404 On fresh install

### ISSUE THREAD

**Issue by pitichampi** [YunoHost-Apps/languagetool_ynh#14]
### Describe the bug

When I try to install the app with untested ngram, I get a 404 there : https://languagetool.org/download/ngram-data/untested/ngram-he-20150915.zip and the install is interrupted.

### Context

- Hardware: VM on a PVE grape
- YunoHost version: 4.3.6.2
- I have access to my server: Through SSH & through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 5.6 (current master branch)

### Steps to reproduce

Just try to install the app with the untested ngram.

### Expected behavior

App successfully installed

### Logs

https://paste.yunohost.org/raw/jelowezeju

**Comment by thsfo** [comment]
same for me ...
