### ISSUE TITLE
Cannot install on rpi3

### ISSUE THREAD

**Issue by theRAGEhero** [YunoHost-Apps/languagetool_ynh#21]
Hello,
I'm trying to install it but I receive this error:

```
2022-10-17 12:29:54,547: DEBUG - + out='https://languagetool.org/download/ngram-data/untested/ngram-he-20150915.zip:
2022-10-17 12:29:54,549: DEBUG - 2022-10-17 12:29:54 ERROR 404: Not Found.'
```

full log: https://paste.yunohost.org/raw/pipakosame

Thank you.

**Comment by Jules-Bertholet** [comment]
This is strange, it looks like you are hitting a bug in an old version of the installation script, that was fixed 1 month ago. Are you sure you tried to install the latest version?

**Comment by theRAGEhero** [comment]
Thank you for you reply.

I updated ynh and now I don't have this error anymore.
